import {
  pgTable,
  text,
  timestamp,
  uuid,
  integer,
  real,
  jsonb,
} from "drizzle-orm/pg-core";
import { user } from "./auth-schema";

export const topics = pgTable("topics", {
  id: uuid("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  lessonContent: text("lesson_content"),
  // Spaced repetition state
  completedAt: timestamp("completed_at"),
  nextReviewAt: timestamp("next_review_at"),
  reviewCount: integer("review_count").default(0).notNull(),
  easeFactor: real("ease_factor").default(2.5).notNull(), // SM-2 algorithm
  interval: integer("interval").default(0).notNull(), // days until next review
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const lessons = pgTable("lessons", {
  id: uuid("id").primaryKey(),
  topicId: uuid("topic_id")
    .notNull()
    .references(() => topics.id, { onDelete: "cascade" }),
  type: text("type", { enum: ["initial", "review"] }).notNull(),
  content: text("content").notNull(), // markdown with :::mcq blocks
  reviewNumber: integer("review_number").notNull().default(0), // 0 for initial, 1+ for reviews
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const quizItems = pgTable("quiz_items", {
  id: uuid("id").primaryKey(),
  lessonId: uuid("lesson_id")
    .notNull()
    .references(() => lessons.id, { onDelete: "cascade" }),
  type: text("type", {
    enum: ["mcq", "short_answer", "long_answer"],
  }).notNull(),
  question: text("question").notNull(),
  config: jsonb("config").notNull(), // type-specific configuration
  orderIndex: integer("order_index").notNull(), // position in lesson
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Export auth tables generated by better-auth CLI
export * from "./auth-schema";
